# Generated by Django 6.0.4 on 2026-05-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='skill',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
